### ISSUE TITLE
[BUG] Both hatch intakes need fixing/rework

### ISSUE THREAD

**Issue by Sonny6155** [CurtinFRC/2019-DeepSpace#126]
The hatch mechanism needs some fixing and overall reworks. The front hatch intake cannot retract the ejector when stowed, and does not automatically retract upon stowing. The side intake also needs to expand (or stay expanded if already) at the start of the match.

**Comment by Sonny6155** [comment]
So turns out both bugs is solved with a one line change. Well then.

**Comment by met4000** [comment]
Not quite done yet...
