### ISSUE TITLE
[BUG] Vision Is Bleeding through & Dislikes switching between hatch and tape

### ISSUE THREAD

**Issue by CJBuchel** [CurtinFRC/2019-DeepSpace#163]
**What happens**
Above is basically it
**What should happen**
Either the bleed is suppose to be seamless and doesn't flicker, this flickers and gives some crazy outputs
**Why it happens (if you know)**
The original image is also being outputted simultaneous with the processing image. Although i don't know why the program doesn't like switching between hatch and tape.
**How to reproduce (make it happen again)**
To properly reproduce it, you need a robot and then deploy to it. View the image and then BAM

**Comment by met4000** [comment]
Is this still to-do, or has it been benched?

**Comment by CJBuchel** [comment]
wontfix
no point, and not worth the effort. our code was overly complicated for no good reason. i've completely remade it
