### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by CJBuchel** [CurtinFRC/2019-DeepSpace#48]
**What we need**
Thread Locking in Vision Tracking
**Some considerations**
uhhhh, don't do it badly?
**Who should do it**
CJ, Song, Joseph
_Don't forget to assign your issue and add it to the project. Labels are nice, too_

**Comment by met4000** [comment]
Why does this have the 'bug' tag? Shouldn't it havethe feature tag?

**Comment by CJBuchel** [comment]
because the current version that is pull requested has a bug in the thread locking

**Comment by CJBuchel** [comment]
so it's a bug and a feature i guess

**Comment by Sonny6155** [comment]
> The naming of this issue gives me a headache

It's not an issue, it's a [FEATURE].
