### ISSUE TITLE
Clean up drive strategies

### ISSUE THREAD

**Issue by JacisNonsense** [CurtinFRC/2019-DeepSpace#86]
We should clean up the strategies such that the strategies in common are completely done in common (including OnUpdate), instead of relying on the user program to impl a single, cherry-picked method. The implementation should be in common or team code as a whole, not split.

**Comment by met4000** [comment]
The reason I did it this way is for Joy input; 5663 has no ControlMap file, and it is definately not identical to ours; esp as they have xbox controllers vs our joystick ones. In future I will try to make generalisations of the joysticks to help with this stuff, but that's in the future; lots of other stuff (including, in my mind, the initilaiser list stuff to make JoystickGroup work properly) has higher priority.
